export const paths = {
    login: '/login',
    root: '/',
    agenda: '/agenda',
    clients: '/clientes',
    tasks: '/tarefas',
    payments: '/pagamentos',
    quotes: '/orcamentos',
    users: '/usuarios',
    reports: '/relatorios',
    settings: '/configuracoes',
    contasPagar: '/contas-pagar',
    contasReceber: '/contas-receber',
    clientDetails: '/clientes/:id',
    orcamentos: '/orcamentos',
    orcamentoDetails: '/orcamentos/:id',
    relatorios: '/relatorios',
    clientesRelatorio: '/relatorios/clientes',
    financeiroRelatorio: '/relatorios/financeiro',
    agendaRelatorio: '/relatorios/agenda',
    geralRelatorio: '/relatorios/geral',
    configuracoes: '/configuracoes',
  } as const;